/*
 *   Script to retrieve ISO 3166-3 information from https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
 *
 *   Written by Steven Huynh-Tran
 *   LinkedIn:   https://linkedin.com/stevenht
 *   Website:    https://stevenhtran.com
 *   Github:     https://github.com/htransteven
 */

const getCountryInfo = () => {
  let data = document.getElementsByClassName("jquery-tablesorter")[0];
  let tbody = data.children[1];
  let trChildren = tbody.children;

  let isoData = {};

  for (let i = 0; i < trChildren.length; i++) {
    const countryObj = {};
    const tdNameChildren = trChildren[i].children[0].children;
    if (!tdNameChildren) continue;
    for (const child of tdNameChildren) {
      if (child.tagName === "A") {
        countryObj["name"] = child.innerText;
        break;
      }
    }
    const tdAlpha2 = trChildren[i].children[3];
    if (!tdAlpha2) continue;
    countryObj["alphaTwo"] = tdAlpha2.children[0].children[1].innerText;
    const tdAlpha3 = trChildren[i].children[4];
    if (!tdAlpha3) continue;
    countryObj["alphaThree"] = tdAlpha3.children[0].children[1].innerText;
    const tdNumCode = trChildren[i].children[5];
    if (!tdNumCode) continue;
    countryObj["numCode"] = tdNumCode.children[0].children[1].innerText;

    isoData[countryObj.alphaTwo] = countryObj;
  }

  return isoData;
};

/*
 *   Data from https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
 *   Post-processed by hand to remove '(the)'
 */

const countries = {
  AF: {
    name: "Afghanistan",
    alphaTwo: "AF",
    alphaThree: "AFG",
    numCode: "004",
  },
  AX: {
    name: "Åland Islands",
    alphaTwo: "AX",
    alphaThree: "ALA",
    numCode: "248",
  },
  AL: { name: "Albania", alphaTwo: "AL", alphaThree: "ALB", numCode: "008" },
  DZ: { name: "Algeria", alphaTwo: "DZ", alphaThree: "DZA", numCode: "012" },
  AS: {
    name: "American Samoa",
    alphaTwo: "AS",
    alphaThree: "ASM",
    numCode: "016",
  },
  AD: { name: "Andorra", alphaTwo: "AD", alphaThree: "AND", numCode: "020" },
  AO: { name: "Angola", alphaTwo: "AO", alphaThree: "AGO", numCode: "024" },
  AI: { name: "Anguilla", alphaTwo: "AI", alphaThree: "AIA", numCode: "660" },
  AQ: { name: "Antarctica", alphaTwo: "AQ", alphaThree: "ATA", numCode: "010" },
  AG: {
    name: "Antigua and Barbuda",
    alphaTwo: "AG",
    alphaThree: "ATG",
    numCode: "028",
  },
  AR: { name: "Argentina", alphaTwo: "AR", alphaThree: "ARG", numCode: "032" },
  AM: { name: "Armenia", alphaTwo: "AM", alphaThree: "ARM", numCode: "051" },
  AW: { name: "Aruba", alphaTwo: "AW", alphaThree: "ABW", numCode: "533" },
  AU: { name: "Australia", alphaTwo: "AU", alphaThree: "AUS", numCode: "036" },
  AT: { name: "Austria", alphaTwo: "AT", alphaThree: "AUT", numCode: "040" },
  AZ: { name: "Azerbaijan", alphaTwo: "AZ", alphaThree: "AZE", numCode: "031" },
  BS: {
    name: "Bahamas",
    alphaTwo: "BS",
    alphaThree: "BHS",
    numCode: "044",
  },
  BH: { name: "Bahrain", alphaTwo: "BH", alphaThree: "BHR", numCode: "048" },
  BD: { name: "Bangladesh", alphaTwo: "BD", alphaThree: "BGD", numCode: "050" },
  BB: { name: "Barbados", alphaTwo: "BB", alphaThree: "BRB", numCode: "052" },
  BY: { name: "Belarus", alphaTwo: "BY", alphaThree: "BLR", numCode: "112" },
  BE: { name: "Belgium", alphaTwo: "BE", alphaThree: "BEL", numCode: "056" },
  BZ: { name: "Belize", alphaTwo: "BZ", alphaThree: "BLZ", numCode: "084" },
  BJ: { name: "Benin", alphaTwo: "BJ", alphaThree: "BEN", numCode: "204" },
  BM: { name: "Bermuda", alphaTwo: "BM", alphaThree: "BMU", numCode: "060" },
  BT: { name: "Bhutan", alphaTwo: "BT", alphaThree: "BTN", numCode: "064" },
  BO: {
    name: "Bolivia",
    alphaTwo: "BO",
    alphaThree: "BOL",
    numCode: "068",
  },
  BQ: { name: "Bonaire", alphaTwo: "BQ", alphaThree: "BES", numCode: "535" },
  BA: {
    name: "Bosnia and Herzegovina",
    alphaTwo: "BA",
    alphaThree: "BIH",
    numCode: "070",
  },
  BW: { name: "Botswana", alphaTwo: "BW", alphaThree: "BWA", numCode: "072" },
  BV: {
    name: "Bouvet Island",
    alphaTwo: "BV",
    alphaThree: "BVT",
    numCode: "074",
  },
  BR: { name: "Brazil", alphaTwo: "BR", alphaThree: "BRA", numCode: "076" },
  IO: {
    name: "British Indian Ocean Territory",
    alphaTwo: "IO",
    alphaThree: "IOT",
    numCode: "086",
  },
  BN: {
    name: "Brunei Darussalam",
    alphaTwo: "BN",
    alphaThree: "BRN",
    numCode: "096",
  },
  BG: { name: "Bulgaria", alphaTwo: "BG", alphaThree: "BGR", numCode: "100" },
  BF: {
    name: "Burkina Faso",
    alphaTwo: "BF",
    alphaThree: "BFA",
    numCode: "854",
  },
  BI: { name: "Burundi", alphaTwo: "BI", alphaThree: "BDI", numCode: "108" },
  CV: { name: "Cabo Verde", alphaTwo: "CV", alphaThree: "CPV", numCode: "132" },
  KH: { name: "Cambodia", alphaTwo: "KH", alphaThree: "KHM", numCode: "116" },
  CM: { name: "Cameroon", alphaTwo: "CM", alphaThree: "CMR", numCode: "120" },
  CA: { name: "Canada", alphaTwo: "CA", alphaThree: "CAN", numCode: "124" },
  KY: {
    name: "Cayman Islands",
    alphaTwo: "KY",
    alphaThree: "CYM",
    numCode: "136",
  },
  CF: {
    name: "Central African Republic",
    alphaTwo: "CF",
    alphaThree: "CAF",
    numCode: "140",
  },
  TD: { name: "Chad", alphaTwo: "TD", alphaThree: "TCD", numCode: "148" },
  CL: { name: "Chile", alphaTwo: "CL", alphaThree: "CHL", numCode: "152" },
  CN: { name: "China", alphaTwo: "CN", alphaThree: "CHN", numCode: "156" },
  CX: {
    name: "Christmas Island",
    alphaTwo: "CX",
    alphaThree: "CXR",
    numCode: "162",
  },
  CC: {
    name: "Cocos (Keeling) Islands",
    alphaTwo: "CC",
    alphaThree: "CCK",
    numCode: "166",
  },
  CO: { name: "Colombia", alphaTwo: "CO", alphaThree: "COL", numCode: "170" },
  KM: {
    name: "Comoros",
    alphaTwo: "KM",
    alphaThree: "COM",
    numCode: "174",
  },
  CD: {
    name: "Democratic Republic of the Congo",
    alphaTwo: "CD",
    alphaThree: "COD",
    numCode: "180",
  },
  CG: {
    name: "Congo",
    alphaTwo: "CG",
    alphaThree: "COG",
    numCode: "178",
  },
  CK: {
    name: "Cook Islands",
    alphaTwo: "CK",
    alphaThree: "COK",
    numCode: "184",
  },
  CR: { name: "Costa Rica", alphaTwo: "CR", alphaThree: "CRI", numCode: "188" },
  CI: {
    name: "Côte d'Ivoire",
    alphaTwo: "CI",
    alphaThree: "CIV",
    numCode: "384",
  },
  HR: { name: "Croatia", alphaTwo: "HR", alphaThree: "HRV", numCode: "191" },
  CU: { name: "Cuba", alphaTwo: "CU", alphaThree: "CUB", numCode: "192" },
  CW: { name: "Curaçao", alphaTwo: "CW", alphaThree: "CUW", numCode: "531" },
  CY: { name: "Cyprus", alphaTwo: "CY", alphaThree: "CYP", numCode: "196" },
  CZ: { name: "Czechia", alphaTwo: "CZ", alphaThree: "CZE", numCode: "203" },
  DK: { name: "Denmark", alphaTwo: "DK", alphaThree: "DNK", numCode: "208" },
  DJ: { name: "Djibouti", alphaTwo: "DJ", alphaThree: "DJI", numCode: "262" },
  DM: { name: "Dominica", alphaTwo: "DM", alphaThree: "DMA", numCode: "212" },
  DO: {
    name: "Dominican Republic",
    alphaTwo: "DO",
    alphaThree: "DOM",
    numCode: "214",
  },
  EC: { name: "Ecuador", alphaTwo: "EC", alphaThree: "ECU", numCode: "218" },
  EG: { name: "Egypt", alphaTwo: "EG", alphaThree: "EGY", numCode: "818" },
  SV: {
    name: "El Salvador",
    alphaTwo: "SV",
    alphaThree: "SLV",
    numCode: "222",
  },
  GQ: {
    name: "Equatorial Guinea",
    alphaTwo: "GQ",
    alphaThree: "GNQ",
    numCode: "226",
  },
  ER: { name: "Eritrea", alphaTwo: "ER", alphaThree: "ERI", numCode: "232" },
  EE: { name: "Estonia", alphaTwo: "EE", alphaThree: "EST", numCode: "233" },
  SZ: { name: "Eswatini", alphaTwo: "SZ", alphaThree: "SWZ", numCode: "748" },
  ET: { name: "Ethiopia", alphaTwo: "ET", alphaThree: "ETH", numCode: "231" },
  FK: {
    name: "Falkland Islands [Malvinas]",
    alphaTwo: "FK",
    alphaThree: "FLK",
    numCode: "238",
  },
  FO: {
    name: "Faroe Islands",
    alphaTwo: "FO",
    alphaThree: "FRO",
    numCode: "234",
  },
  FJ: { name: "Fiji", alphaTwo: "FJ", alphaThree: "FJI", numCode: "242" },
  FI: { name: "Finland", alphaTwo: "FI", alphaThree: "FIN", numCode: "246" },
  FR: { name: "France", alphaTwo: "FR", alphaThree: "FRA", numCode: "250" },
  GF: {
    name: "French Guiana",
    alphaTwo: "GF",
    alphaThree: "GUF",
    numCode: "254",
  },
  PF: {
    name: "French Polynesia",
    alphaTwo: "PF",
    alphaThree: "PYF",
    numCode: "258",
  },
  TF: {
    name: "French Southern Territories",
    alphaTwo: "TF",
    alphaThree: "ATF",
    numCode: "260",
  },
  GA: { name: "Gabon", alphaTwo: "GA", alphaThree: "GAB", numCode: "266" },
  GM: {
    name: "Gambia",
    alphaTwo: "GM",
    alphaThree: "GMB",
    numCode: "270",
  },
  GE: { name: "Georgia", alphaTwo: "GE", alphaThree: "GEO", numCode: "268" },
  DE: { name: "Germany", alphaTwo: "DE", alphaThree: "DEU", numCode: "276" },
  GH: { name: "Ghana", alphaTwo: "GH", alphaThree: "GHA", numCode: "288" },
  GI: { name: "Gibraltar", alphaTwo: "GI", alphaThree: "GIB", numCode: "292" },
  GR: { name: "Greece", alphaTwo: "GR", alphaThree: "GRC", numCode: "300" },
  GL: { name: "Greenland", alphaTwo: "GL", alphaThree: "GRL", numCode: "304" },
  GD: { name: "Grenada", alphaTwo: "GD", alphaThree: "GRD", numCode: "308" },
  GP: { name: "Guadeloupe", alphaTwo: "GP", alphaThree: "GLP", numCode: "312" },
  GU: { name: "Guam", alphaTwo: "GU", alphaThree: "GUM", numCode: "316" },
  GT: { name: "Guatemala", alphaTwo: "GT", alphaThree: "GTM", numCode: "320" },
  GG: { name: "Guernsey", alphaTwo: "GG", alphaThree: "GGY", numCode: "831" },
  GN: { name: "Guinea", alphaTwo: "GN", alphaThree: "GIN", numCode: "324" },
  GW: {
    name: "Guinea-Bissau",
    alphaTwo: "GW",
    alphaThree: "GNB",
    numCode: "624",
  },
  GY: { name: "Guyana", alphaTwo: "GY", alphaThree: "GUY", numCode: "328" },
  HT: { name: "Haiti", alphaTwo: "HT", alphaThree: "HTI", numCode: "332" },
  HM: {
    name: "Heard Island and McDonald Islands",
    alphaTwo: "HM",
    alphaThree: "HMD",
    numCode: "334",
  },
  VA: {
    name: "Holy See",
    alphaTwo: "VA",
    alphaThree: "VAT",
    numCode: "336",
  },
  HN: { name: "Honduras", alphaTwo: "HN", alphaThree: "HND", numCode: "340" },
  HK: { name: "Hong Kong", alphaTwo: "HK", alphaThree: "HKG", numCode: "344" },
  HU: { name: "Hungary", alphaTwo: "HU", alphaThree: "HUN", numCode: "348" },
  IS: { name: "Iceland", alphaTwo: "IS", alphaThree: "ISL", numCode: "352" },
  IN: { name: "India", alphaTwo: "IN", alphaThree: "IND", numCode: "356" },
  ID: { name: "Indonesia", alphaTwo: "ID", alphaThree: "IDN", numCode: "360" },
  IR: {
    name: "Iran",
    alphaTwo: "IR",
    alphaThree: "IRN",
    numCode: "364",
  },
  IQ: { name: "Iraq", alphaTwo: "IQ", alphaThree: "IRQ", numCode: "368" },
  IE: { name: "Ireland", alphaTwo: "IE", alphaThree: "IRL", numCode: "372" },
  IM: {
    name: "Isle of Man",
    alphaTwo: "IM",
    alphaThree: "IMN",
    numCode: "833",
  },
  IL: { name: "Israel", alphaTwo: "IL", alphaThree: "ISR", numCode: "376" },
  IT: { name: "Italy", alphaTwo: "IT", alphaThree: "ITA", numCode: "380" },
  JM: { name: "Jamaica", alphaTwo: "JM", alphaThree: "JAM", numCode: "388" },
  JP: { name: "Japan", alphaTwo: "JP", alphaThree: "JPN", numCode: "392" },
  JE: { name: "Jersey", alphaTwo: "JE", alphaThree: "JEY", numCode: "832" },
  JO: { name: "Jordan", alphaTwo: "JO", alphaThree: "JOR", numCode: "400" },
  KZ: { name: "Kazakhstan", alphaTwo: "KZ", alphaThree: "KAZ", numCode: "398" },
  KE: { name: "Kenya", alphaTwo: "KE", alphaThree: "KEN", numCode: "404" },
  KI: { name: "Kiribati", alphaTwo: "KI", alphaThree: "KIR", numCode: "296" },
  KP: {
    name: "Democratic People's Republic of Korea",
    alphaTwo: "KP",
    alphaThree: "PRK",
    numCode: "408",
  },
  KR: {
    name: "Republic of Korea",
    alphaTwo: "KR",
    alphaThree: "KOR",
    numCode: "410",
  },
  KW: { name: "Kuwait", alphaTwo: "KW", alphaThree: "KWT", numCode: "414" },
  KG: { name: "Kyrgyzstan", alphaTwo: "KG", alphaThree: "KGZ", numCode: "417" },
  LA: {
    name: "Lao People's Democratic Republic)",
    alphaTwo: "LA",
    alphaThree: "LAO",
    numCode: "418",
  },
  LV: { name: "Latvia", alphaTwo: "LV", alphaThree: "LVA", numCode: "428" },
  LB: { name: "Lebanon", alphaTwo: "LB", alphaThree: "LBN", numCode: "422" },
  LS: { name: "Lesotho", alphaTwo: "LS", alphaThree: "LSO", numCode: "426" },
  LR: { name: "Liberia", alphaTwo: "LR", alphaThree: "LBR", numCode: "430" },
  LY: { name: "Libya", alphaTwo: "LY", alphaThree: "LBY", numCode: "434" },
  LI: {
    name: "Liechtenstein",
    alphaTwo: "LI",
    alphaThree: "LIE",
    numCode: "438",
  },
  LT: { name: "Lithuania", alphaTwo: "LT", alphaThree: "LTU", numCode: "440" },
  LU: { name: "Luxembourg", alphaTwo: "LU", alphaThree: "LUX", numCode: "442" },
  MO: { name: "Macao", alphaTwo: "MO", alphaThree: "MAC", numCode: "446" },
  MK: {
    name: "North Macedonia",
    alphaTwo: "MK",
    alphaThree: "MKD",
    numCode: "807",
  },
  MG: { name: "Madagascar", alphaTwo: "MG", alphaThree: "MDG", numCode: "450" },
  MW: { name: "Malawi", alphaTwo: "MW", alphaThree: "MWI", numCode: "454" },
  MY: { name: "Malaysia", alphaTwo: "MY", alphaThree: "MYS", numCode: "458" },
  MV: { name: "Maldives", alphaTwo: "MV", alphaThree: "MDV", numCode: "462" },
  ML: { name: "Mali", alphaTwo: "ML", alphaThree: "MLI", numCode: "466" },
  MT: { name: "Malta", alphaTwo: "MT", alphaThree: "MLT", numCode: "470" },
  MH: {
    name: "Marshall Islands",
    alphaTwo: "MH",
    alphaThree: "MHL",
    numCode: "584",
  },
  MQ: { name: "Martinique", alphaTwo: "MQ", alphaThree: "MTQ", numCode: "474" },
  MR: { name: "Mauritania", alphaTwo: "MR", alphaThree: "MRT", numCode: "478" },
  MU: { name: "Mauritius", alphaTwo: "MU", alphaThree: "MUS", numCode: "480" },
  YT: { name: "Mayotte", alphaTwo: "YT", alphaThree: "MYT", numCode: "175" },
  MX: { name: "Mexico", alphaTwo: "MX", alphaThree: "MEX", numCode: "484" },
  FM: {
    name: "Micronesia",
    alphaTwo: "FM",
    alphaThree: "FSM",
    numCode: "583",
  },
  MD: {
    name: "Moldova",
    alphaTwo: "MD",
    alphaThree: "MDA",
    numCode: "498",
  },
  MC: { name: "Monaco", alphaTwo: "MC", alphaThree: "MCO", numCode: "492" },
  MN: { name: "Mongolia", alphaTwo: "MN", alphaThree: "MNG", numCode: "496" },
  ME: { name: "Montenegro", alphaTwo: "ME", alphaThree: "MNE", numCode: "499" },
  MS: { name: "Montserrat", alphaTwo: "MS", alphaThree: "MSR", numCode: "500" },
  MA: { name: "Morocco", alphaTwo: "MA", alphaThree: "MAR", numCode: "504" },
  MZ: { name: "Mozambique", alphaTwo: "MZ", alphaThree: "MOZ", numCode: "508" },
  MM: { name: "Myanmar", alphaTwo: "MM", alphaThree: "MMR", numCode: "104" },
  NA: { name: "Namibia", alphaTwo: "NA", alphaThree: "NAM", numCode: "516" },
  NR: { name: "Nauru", alphaTwo: "NR", alphaThree: "NRU", numCode: "520" },
  NP: { name: "Nepal", alphaTwo: "NP", alphaThree: "NPL", numCode: "524" },
  NL: {
    name: "Netherlands",
    alphaTwo: "NL",
    alphaThree: "NLD",
    numCode: "528",
  },
  NC: {
    name: "New Caledonia",
    alphaTwo: "NC",
    alphaThree: "NCL",
    numCode: "540",
  },
  NZ: {
    name: "New Zealand",
    alphaTwo: "NZ",
    alphaThree: "NZL",
    numCode: "554",
  },
  NI: { name: "Nicaragua", alphaTwo: "NI", alphaThree: "NIC", numCode: "558" },
  NE: {
    name: "Niger",
    alphaTwo: "NE",
    alphaThree: "NER",
    numCode: "562",
  },
  NG: { name: "Nigeria", alphaTwo: "NG", alphaThree: "NGA", numCode: "566" },
  NU: { name: "Niue", alphaTwo: "NU", alphaThree: "NIU", numCode: "570" },
  NF: {
    name: "Norfolk Island",
    alphaTwo: "NF",
    alphaThree: "NFK",
    numCode: "574",
  },
  MP: {
    name: "Northern Mariana Islands",
    alphaTwo: "MP",
    alphaThree: "MNP",
    numCode: "580",
  },
  NO: { name: "Norway", alphaTwo: "NO", alphaThree: "NOR", numCode: "578" },
  OM: { name: "Oman", alphaTwo: "OM", alphaThree: "OMN", numCode: "512" },
  PK: { name: "Pakistan", alphaTwo: "PK", alphaThree: "PAK", numCode: "586" },
  PW: { name: "Palau", alphaTwo: "PW", alphaThree: "PLW", numCode: "585" },
  PS: {
    name: "Palestine, State of",
    alphaTwo: "PS",
    alphaThree: "PSE",
    numCode: "275",
  },
  PA: { name: "Panama", alphaTwo: "PA", alphaThree: "PAN", numCode: "591" },
  PG: {
    name: "Papua New Guinea",
    alphaTwo: "PG",
    alphaThree: "PNG",
    numCode: "598",
  },
  PY: { name: "Paraguay", alphaTwo: "PY", alphaThree: "PRY", numCode: "600" },
  PE: { name: "Peru", alphaTwo: "PE", alphaThree: "PER", numCode: "604" },
  PH: {
    name: "Philippines",
    alphaTwo: "PH",
    alphaThree: "PHL",
    numCode: "608",
  },
  PN: { name: "Pitcairn", alphaTwo: "PN", alphaThree: "PCN", numCode: "612" },
  PL: { name: "Poland", alphaTwo: "PL", alphaThree: "POL", numCode: "616" },
  PT: { name: "Portugal", alphaTwo: "PT", alphaThree: "PRT", numCode: "620" },
  PR: {
    name: "Puerto Rico",
    alphaTwo: "PR",
    alphaThree: "PRI",
    numCode: "630",
  },
  QA: { name: "Qatar", alphaTwo: "QA", alphaThree: "QAT", numCode: "634" },
  RE: { name: "Réunion", alphaTwo: "RE", alphaThree: "REU", numCode: "638" },
  RO: { name: "Romania", alphaTwo: "RO", alphaThree: "ROU", numCode: "642" },
  RU: {
    name: "Russian Federation",
    alphaTwo: "RU",
    alphaThree: "RUS",
    numCode: "643",
  },
  RW: { name: "Rwanda", alphaTwo: "RW", alphaThree: "RWA", numCode: "646" },
  BL: {
    name: "Saint Barthélemy",
    alphaTwo: "BL",
    alphaThree: "BLM",
    numCode: "652",
  },
  SH: {
    name: "Saint Helena",
    alphaTwo: "SH",
    alphaThree: "SHN",
    numCode: "654",
  },
  KN: {
    name: "Saint Kitts and Nevis",
    alphaTwo: "KN",
    alphaThree: "KNA",
    numCode: "659",
  },
  LC: {
    name: "Saint Lucia",
    alphaTwo: "LC",
    alphaThree: "LCA",
    numCode: "662",
  },
  MF: {
    name: "Saint Martin",
    alphaTwo: "MF",
    alphaThree: "MAF",
    numCode: "663",
  },
  PM: {
    name: "Saint Pierre and Miquelon",
    alphaTwo: "PM",
    alphaThree: "SPM",
    numCode: "666",
  },
  VC: {
    name: "Saint Vincent and the Grenadines",
    alphaTwo: "VC",
    alphaThree: "VCT",
    numCode: "670",
  },
  WS: { name: "Samoa", alphaTwo: "WS", alphaThree: "WSM", numCode: "882" },
  SM: { name: "San Marino", alphaTwo: "SM", alphaThree: "SMR", numCode: "674" },
  ST: {
    name: "Sao Tome and Principe",
    alphaTwo: "ST",
    alphaThree: "STP",
    numCode: "678",
  },
  SA: {
    name: "Saudi Arabia",
    alphaTwo: "SA",
    alphaThree: "SAU",
    numCode: "682",
  },
  SN: { name: "Senegal", alphaTwo: "SN", alphaThree: "SEN", numCode: "686" },
  RS: { name: "Serbia", alphaTwo: "RS", alphaThree: "SRB", numCode: "688" },
  SC: { name: "Seychelles", alphaTwo: "SC", alphaThree: "SYC", numCode: "690" },
  SL: {
    name: "Sierra Leone",
    alphaTwo: "SL",
    alphaThree: "SLE",
    numCode: "694",
  },
  SG: { name: "Singapore", alphaTwo: "SG", alphaThree: "SGP", numCode: "702" },
  SX: {
    name: "Sint Maarten",
    alphaTwo: "SX",
    alphaThree: "SXM",
    numCode: "534",
  },
  SK: { name: "Slovakia", alphaTwo: "SK", alphaThree: "SVK", numCode: "703" },
  SI: { name: "Slovenia", alphaTwo: "SI", alphaThree: "SVN", numCode: "705" },
  SB: {
    name: "Solomon Islands",
    alphaTwo: "SB",
    alphaThree: "SLB",
    numCode: "090",
  },
  SO: { name: "Somalia", alphaTwo: "SO", alphaThree: "SOM", numCode: "706" },
  ZA: {
    name: "South Africa",
    alphaTwo: "ZA",
    alphaThree: "ZAF",
    numCode: "710",
  },
  GS: {
    name: "South Georgia and the South Sandwich Islands",
    alphaTwo: "GS",
    alphaThree: "SGS",
    numCode: "239",
  },
  SS: {
    name: "South Sudan",
    alphaTwo: "SS",
    alphaThree: "SSD",
    numCode: "728",
  },
  ES: { name: "Spain", alphaTwo: "ES", alphaThree: "ESP", numCode: "724" },
  LK: { name: "Sri Lanka", alphaTwo: "LK", alphaThree: "LKA", numCode: "144" },
  SD: {
    name: "Sudan",
    alphaTwo: "SD",
    alphaThree: "SDN",
    numCode: "729",
  },
  SR: { name: "Suriname", alphaTwo: "SR", alphaThree: "SUR", numCode: "740" },
  SJ: { name: "Svalbard", alphaTwo: "SJ", alphaThree: "SJM", numCode: "744" },
  SE: { name: "Sweden", alphaTwo: "SE", alphaThree: "SWE", numCode: "752" },
  CH: {
    name: "Switzerland",
    alphaTwo: "CH",
    alphaThree: "CHE",
    numCode: "756",
  },
  SY: {
    name: "Syrian Arab Republic",
    alphaTwo: "SY",
    alphaThree: "SYR",
    numCode: "760",
  },
  TW: {
    name: "Taiwan",
    alphaTwo: "TW",
    alphaThree: "TWN",
    numCode: "158",
  },
  TJ: { name: "Tajikistan", alphaTwo: "TJ", alphaThree: "TJK", numCode: "762" },
  TZ: {
    name: "United Republic of Tanzania",
    alphaTwo: "TZ",
    alphaThree: "TZA",
    numCode: "834",
  },
  TH: { name: "Thailand", alphaTwo: "TH", alphaThree: "THA", numCode: "764" },
  TL: {
    name: "Timor-Leste",
    alphaTwo: "TL",
    alphaThree: "TLS",
    numCode: "626",
  },
  TG: { name: "Togo", alphaTwo: "TG", alphaThree: "TGO", numCode: "768" },
  TK: { name: "Tokelau", alphaTwo: "TK", alphaThree: "TKL", numCode: "772" },
  TO: { name: "Tonga", alphaTwo: "TO", alphaThree: "TON", numCode: "776" },
  TT: {
    name: "Trinidad and Tobago",
    alphaTwo: "TT",
    alphaThree: "TTO",
    numCode: "780",
  },
  TN: { name: "Tunisia", alphaTwo: "TN", alphaThree: "TUN", numCode: "788" },
  TR: { name: "Turkey", alphaTwo: "TR", alphaThree: "TUR", numCode: "792" },
  TM: {
    name: "Turkmenistan",
    alphaTwo: "TM",
    alphaThree: "TKM",
    numCode: "795",
  },
  TC: {
    name: "Turks and Caicos Islands",
    alphaTwo: "TC",
    alphaThree: "TCA",
    numCode: "796",
  },
  TV: { name: "Tuvalu", alphaTwo: "TV", alphaThree: "TUV", numCode: "798" },
  UG: { name: "Uganda", alphaTwo: "UG", alphaThree: "UGA", numCode: "800" },
  UA: { name: "Ukraine", alphaTwo: "UA", alphaThree: "UKR", numCode: "804" },
  AE: {
    name: "United Arab Emirates",
    alphaTwo: "AE",
    alphaThree: "ARE",
    numCode: "784",
  },
  GB: {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alphaTwo: "GB",
    alphaThree: "GBR",
    numCode: "826",
  },
  UM: {
    name: "United States Minor Outlying Islands",
    alphaTwo: "UM",
    alphaThree: "UMI",
    numCode: "581",
  },
  US: {
    name: "United States of America",
    alphaTwo: "US",
    alphaThree: "USA",
    numCode: "840",
  },
  UY: { name: "Uruguay", alphaTwo: "UY", alphaThree: "URY", numCode: "858" },
  UZ: { name: "Uzbekistan", alphaTwo: "UZ", alphaThree: "UZB", numCode: "860" },
  VU: { name: "Vanuatu", alphaTwo: "VU", alphaThree: "VUT", numCode: "548" },
  VE: {
    name: "Venezuela",
    alphaTwo: "VE",
    alphaThree: "VEN",
    numCode: "862",
  },
  VN: { name: "Viet Nam", alphaTwo: "VN", alphaThree: "VNM", numCode: "704" },
  VG: {
    name: "British Virgin Islands",
    alphaTwo: "VG",
    alphaThree: "VGB",
    numCode: "092",
  },
  VI: {
    name: "U.S. Virgin Islands",
    alphaTwo: "VI",
    alphaThree: "VIR",
    numCode: "850",
  },
  WF: {
    name: "Wallis and Futuna",
    alphaTwo: "WF",
    alphaThree: "WLF",
    numCode: "876",
  },
  EH: {
    name: "Western Sahara",
    alphaTwo: "EH",
    alphaThree: "ESH",
    numCode: "732",
  },
  YE: { name: "Yemen", alphaTwo: "YE", alphaThree: "YEM", numCode: "887" },
  ZM: { name: "Zambia", alphaTwo: "ZM", alphaThree: "ZMB", numCode: "894" },
  ZW: { name: "Zimbabwe", alphaTwo: "ZW", alphaThree: "ZWE", numCode: "716" },
};
